#!/usr/bin/env python3
"""
packages_config_to_csproj.py

Converts one or more packages.config files into synthetic .csproj files
with <PackageReference> entries that Semgrep Supply Chain can consume
via `semgrep ci --allow-local-builds`.

Usage:
    # Single file, output to stdout
    python packages_config_to_csproj.py packages.config

    # Single file, write to specific path
    python packages_config_to_csproj.py packages.config -o MyProject/_semgrep_synthetic.csproj

    # Walk an entire repo and convert every packages.config found
    python packages_config_to_csproj.py --scan-dir ./src

    # Dry run (print what would be created, don't write)
    python packages_config_to_csproj.py --scan-dir ./src --dry-run
"""

import argparse
import sys
import os
import xml.etree.ElementTree as ET
from pathlib import Path


# ---------------------------------------------------------------------------
# Core conversion logic
# ---------------------------------------------------------------------------

def parse_packages_config(path: Path) -> list[dict]:
    """
    Parse a packages.config file and return a list of package dicts:
      [{"id": "Newtonsoft.Json", "version": "13.0.1", "targetFramework": "net48"}, ...]
    """
    try:
        tree = ET.parse(path)
    except ET.ParseError as e:
        raise ValueError(f"XML parse error in {path}: {e}")

    root = tree.getroot()

    # Handle both <packages> root and bare <package> roots (malformed but seen in the wild)
    if root.tag == "packages":
        package_elements = root.findall("package")
    elif root.tag == "package":
        package_elements = [root]
    else:
        raise ValueError(f"Unexpected root element <{root.tag}> in {path}. Expected <packages>.")

    packages = []
    for pkg in package_elements:
        pkg_id = pkg.get("id", "").strip()
        version = pkg.get("version", "").strip()

        if not pkg_id:
            print(f"  [WARN] Skipping package entry with no 'id' attribute in {path}", file=sys.stderr)
            continue
        if not version:
            print(f"  [WARN] Package '{pkg_id}' has no 'version' attribute — skipping", file=sys.stderr)
            continue

        packages.append({
            "id": pkg_id,
            "version": version,
            "targetFramework": pkg.get("targetFramework", "").strip(),
            "developmentDependency": pkg.get("developmentDependency", "false").lower() == "true",
        })

    return packages


def resolve_target_framework(packages: list[dict], fallback: str = "net48") -> str:
    """
    Pick a single TargetFramework for the synthetic .csproj.

    Strategy:
      1. Collect all unique non-empty targetFramework values.
      2. If only one — use it.
      3. If multiple — prefer the highest net* version (simple string sort works for net4x).
      4. If none — use the fallback.
    """
    tfms = sorted(
        set(p["targetFramework"] for p in packages if p["targetFramework"]),
        reverse=True,
    )
    if not tfms:
        return fallback
    if len(tfms) == 1:
        return tfms[0]

    # Multiple TFMs: warn and pick highest
    print(
        f"  [WARN] Multiple targetFramework values found: {tfms}. "
        f"Using '{tfms[0]}'. Consider reviewing the synthetic .csproj.",
        file=sys.stderr,
    )
    return tfms[0]


def build_csproj(packages: list[dict], target_framework: str) -> str:
    """
    Render the synthetic .csproj XML string.
    """
    lines = [
        '<Project Sdk="Microsoft.NET.Sdk">',
        "",
        "  <!-- AUTO-GENERATED by packages_config_to_csproj.py -->",
        "  <!-- DO NOT EDIT — this file exists solely for Semgrep Supply Chain scanning -->",
        "",
        "  <PropertyGroup>",
        f"    <TargetFramework>{target_framework}</TargetFramework>",
        "    <!-- Disable build output so this project is never accidentally compiled -->",
        "    <IsPackable>false</IsPackable>",
        "  </PropertyGroup>",
        "",
        "  <ItemGroup>",
    ]

    for pkg in packages:
        comment = ""
        if pkg["developmentDependency"]:
            comment = "  <!-- dev dependency -->"
        lines.append(
            f'    <PackageReference Include="{pkg["id"]}" Version="{pkg["version"]}" />{comment}'
        )

    lines += [
        "  </ItemGroup>",
        "",
        "</Project>",
    ]

    return "\n".join(lines)


def convert(input_path: Path, output_path: Path | None = None, dry_run: bool = False) -> str | None:
    """
    Full pipeline: parse → resolve TFM → render → optionally write.
    Returns the rendered csproj string (useful for stdout mode).
    """
    packages = parse_packages_config(input_path)

    if not packages:
        print(f"  [WARN] No packages found in {input_path} — skipping.", file=sys.stderr)
        return None

    tfm = resolve_target_framework(packages)
    csproj_content = build_csproj(packages, tfm)

    if output_path is None:
        return csproj_content  # caller will print to stdout

    if dry_run:
        print(f"  [DRY RUN] Would write {len(packages)} packages → {output_path}")
        return csproj_content

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(csproj_content, encoding="utf-8")
    print(f"  [OK] {input_path} → {output_path} ({len(packages)} packages, TFM: {tfm})")
    return csproj_content


# ---------------------------------------------------------------------------
# Directory scan mode
# ---------------------------------------------------------------------------

SYNTHETIC_FILENAME = "_semgrep_synthetic.csproj"


def scan_directory(root_dir: Path, dry_run: bool = False) -> int:
    """
    Recursively find all packages.config files under root_dir and convert each one.
    Returns the count of files processed.
    """
    found = list(root_dir.rglob("packages.config"))

    if not found:
        print(f"No packages.config files found under {root_dir}", file=sys.stderr)
        return 0

    print(f"Found {len(found)} packages.config file(s):\n")
    count = 0
    for cfg_path in found:
        output_path = cfg_path.parent / SYNTHETIC_FILENAME
        try:
            result = convert(cfg_path, output_path, dry_run=dry_run)
            if result is not None:
                count += 1
        except ValueError as e:
            print(f"  [ERROR] {e}", file=sys.stderr)

    return count


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert packages.config → synthetic .csproj for Semgrep Supply Chain",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "input",
        nargs="?",
        metavar="PACKAGES_CONFIG",
        help="Path to a single packages.config file",
    )
    mode.add_argument(
        "--scan-dir",
        metavar="DIR",
        help="Recursively find and convert all packages.config files under DIR",
    )

    parser.add_argument(
        "-o", "--output",
        metavar="OUTPUT_CSPROJ",
        help="Output path for the synthetic .csproj (single-file mode only). Defaults to stdout.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written without writing any files",
    )

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    # --- Scan directory mode ---
    if args.scan_dir:
        root = Path(args.scan_dir)
        if not root.is_dir():
            print(f"ERROR: --scan-dir '{root}' is not a directory.", file=sys.stderr)
            sys.exit(1)
        count = scan_directory(root, dry_run=args.dry_run)
        print(f"\nDone. {count} file(s) converted.")
        sys.exit(0)

    # --- Single file mode ---
    input_path = Path(args.input)
    if not input_path.is_file():
        print(f"ERROR: '{input_path}' not found or is not a file.", file=sys.stderr)
        sys.exit(1)

    output_path = Path(args.output) if args.output else None

    result = convert(input_path, output_path, dry_run=args.dry_run)

    if output_path is None and result is not None:
        print(result)


if __name__ == "__main__":
    main()
